import Head from "next/head";
import Banner from "../components/banner";
import Header from "../components/Header";

export default function Home() {
	return (
		<div className="h-screen">
			<Head>
				<title>Portfolio</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="h-full">
				<Header />
				<Banner />
			</main>
		</div>
	);
}
